# Generated by Django 5.2.5 on 2025-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='important',
            new_name='destacada',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='date_completed',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='title',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='director',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='titulo',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
