# Generated by Django 5.2.5 on 2025-09-16 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_description_pelicula_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='anio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
